image: node:8

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm cache clean --force
          - rm -rf node_modules
          - rm npm-shrinkwrap.json
          - npm shrinkwrap
          - npm install
          - npm start
        services:
          - mongo

definitions:
  services:
    mongo:
      image: mongo