image: node:8.2.0

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm run format
          - npm run webpack
          - npm start